{% set name = "icfree" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/icfree-ml/archive/{{ version }}.tar.gz
  sha256: e5f934b8116f2e17137a985b7f7ccc0e934b87ec3e21301cef6ab966a7ebde9c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - glob2
    - ipython
    - ipywidgets
    - matplotlib-base
    - numpy
    - openpyxl
    - pandas
    - pydoe2
    - python >=3.8,<3.12
    - scikit-learn
    - scipy
    - seaborn
    - xgboost

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - python -m pytest

about:
  home: https://github.com/brsynth/icfree-ml
  summary: Design of experiments (DoE) and machine learning for cell-free
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
    - breakthewall
    - tduigou
