{% set name = "icfree" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/icfree-ml/archive/{{ version }}.tar.gz
  sha256: 9a9279181e9f63c3eff89cc03968bf84cb875d5e30d71fee8fc83e2a42ef09bb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - pydoe2
    - brs_utils
    - scikit-learn

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - cd tests
    - python -m pytest

about:
  home: https://github.com/brsynth/icfree-ml
  summary: Design of experiments (DoE) and machine learning for cell-free
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yorgomoubayed
